# Generated by Django 5.1.1 on 2024-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('print_check_as', models.CharField(blank=True, max_length=100)),
                ('is_employee', models.BooleanField(default=False)),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
                ('ein', models.CharField(blank=True, max_length=15, null=True)),
                ('pay_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Per Mile', 'Per Mile'), ('Flat Rate', 'Flat Rate')], default='Percentage', max_length=50)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assigned_truck', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_trailer', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('annual_review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('drivers_license_number', models.CharField(max_length=50)),
                ('license_state', models.CharField(max_length=2)),
                ('license_expiration_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
