# Generated by Django 5.1.1 on 2024-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Loaded', 'Loaded'), ('Unloaded', 'Unloaded')], default='Pending', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('shipper_in_time', models.DateTimeField(blank=True, null=True)),
                ('shipper_out_time', models.DateTimeField(blank=True, null=True)),
                ('receiver_in_time', models.DateTimeField(blank=True, null=True)),
                ('receiver_out_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
            },
        ),
    ]
