# Generated by Django 5.1.4 on 2025-01-06 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers_operators', '0002_initial'),
        ('loads', '0005_alter_delivery_delivery_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('stop_order', models.PositiveIntegerField()),
                ('pallets_handled', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_handled', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_crossdock', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('shipper_in_time', models.DateTimeField(blank=True, null=True)),
                ('shipper_out_time', models.DateTimeField(blank=True, null=True)),
                ('receiver_in_time', models.DateTimeField(blank=True, null=True)),
                ('receiver_out_time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers_operators.driver')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.load')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
            },
        ),
    ]
