# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('drivers_operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers_operators.driver'),
        ),
    ]
