# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_initial'),
        ('loads', '0001_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.load'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck'),
        ),
        migrations.AddField(
            model_name='dispatchstop',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.dispatch'),
        ),
    ]
