# Generated by Django 5.1.1 on 2024-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_initial'),
        ('equipment', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.load'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.truck'),
        ),
    ]
