# Generated by Django 5.1.1 on 2024-12-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DispatchStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('stop_order', models.PositiveIntegerField()),
                ('pallets_handled', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_handled', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_crossdock', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.dispatch')),
            ],
        ),
    ]
