# Generated by Django 5.1.1 on 2024-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='load',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loads.load'),
        ),
    ]
