# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('shippers_receivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='associated_location',
            field=models.ForeignKey(blank=True, help_text='Location associated with this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shippers_receivers.location'),
        ),
    ]
