# Generated by Django 5.1.1 on 2024-12-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment_remove_invoice_associated_company'),
        ('loads', '0005_alter_delivery_delivery_location_and_more'),
        ('shippers_receivers', '0005_delete_shipperreceivercompany_contact_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='associated_customer',
            field=models.ForeignKey(blank=True, help_text='Customer responsible for this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shippers_receivers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='associated_location',
            field=models.ForeignKey(blank=True, help_text='Location associated with this invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shippers_receivers.location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Track if the invoice has been paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='load',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='loads.load'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
