# Generated by Django 5.1.1 on 2025-01-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='User who issued this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser'),
        ),
    ]
