# Generated by Django 5.1.1 on 2024-12-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoice_associated_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='associated_customer',
        ),
    ]
