# Generated by Django 5.1.1 on 2024-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samsara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('engine_hours', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('samsara_device_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('truck_number', models.CharField(blank=True, max_length=20, null=True)),
                ('samsara_device_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('inspection_due', models.DateField()),
                ('registration_exp', models.DateField()),
                ('insurance_exp', models.DateField()),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('tire_size', models.CharField(blank=True, max_length=50)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axles', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unladen_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('downpayment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('sold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.operationalcompany')),
            ],
        ),
    ]
