# Generated by Django 5.1.1 on 2024-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shippers_receivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trailer_type', models.CharField(choices=[('Dry Van', 'Dry Van'), ('Van or Reefer', 'Van or Reefer'), ('Reefer', 'Reefer')], default='Dry Van', max_length=50)),
                ('load_type', models.CharField(choices=[('Full Load', 'Full Load'), ('LTL', 'LTL')], default='Full Load', max_length=10)),
                ('feet_required', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('pallet_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pallet_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('commodity', models.CharField(default='Unknown commodity', max_length=255)),
                ('pickup_location', models.CharField(default='Unknown', max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Booked', editable=False, max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_number', models.PositiveIntegerField()),
                ('pickup_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.PositiveIntegerField()),
                ('delivery_date', models.DateTimeField()),
                ('delivery_location', models.ForeignKey(limit_choices_to={'is_receiver': True}, on_delete=django.db.models.deletion.CASCADE, to='shippers_receivers.shipperreceivercompany')),
            ],
        ),
    ]
