# Generated by Django 5.1.1 on 2024-09-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loads', '0001_initial'),
        ('shippers_receivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='loads.load'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='loads.load'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='pickup_location',
            field=models.ForeignKey(limit_choices_to={'is_shipper': True}, on_delete=django.db.models.deletion.CASCADE, to='shippers_receivers.shipperreceivercompany'),
        ),
    ]
