# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loads', '0001_initial'),
        ('shippers_receivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_location',
            field=models.ForeignKey(limit_choices_to={'is_receiver': True}, on_delete=django.db.models.deletion.CASCADE, to='shippers_receivers.location'),
        ),
    ]
