# Generated by Django 5.1.2 on 2024-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='load_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='reference_number',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
