# Generated by Django 5.1.1 on 2024-12-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0004_alter_load_booked_by'),
        ('shippers_receivers', '0004_category_contact_customer_location_locationphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_location',
            field=models.ForeignKey(limit_choices_to={'is_receiver': True}, on_delete=django.db.models.deletion.CASCADE, to='shippers_receivers.location'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup_location',
            field=models.ForeignKey(limit_choices_to={'is_shipper': True}, on_delete=django.db.models.deletion.CASCADE, to='shippers_receivers.location'),
        ),
    ]
