# Generated by Django 5.1.1 on 2024-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mc_number', models.CharField(blank=True, max_length=7, null=True)),
                ('scac', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(default='Default Address', max_length=255)),
                ('address_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(default='Default City', max_length=100)),
                ('state', models.CharField(default='Default State', max_length=100)),
                ('zip_code', models.CharField(default='00000', max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('cell_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('accounting_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('broker_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('term_pay', models.CharField(choices=[('Net 30', 'Net 30'), ('Net 15', 'Net 15')], default='Net 30', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('factoring', models.BooleanField(default=False)),
                ('do_not_use', models.BooleanField(default=False)),
                ('whitelist', models.BooleanField(default=False)),
                ('accounts_payable_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_payable_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('accounts_payable_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('accounts_payable_address', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_payable_city', models.CharField(blank=True, max_length=100, null=True)),
                ('accounts_payable_state', models.CharField(blank=True, max_length=100, null=True)),
                ('accounts_payable_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
