# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('mc_number', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_mc_number', message='MC Number must be up to 7 digits long.', regex='^\\d{1,7}$')])),
                ('scac', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message="ZIP Code must be in the format '12345' or '12345-6789'.", regex='^\\d{5}(-\\d{4})?$')])),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be in the format (000)000-0000.', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')])),
                ('cell_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cell_number', message='Cell number must be in the format (000)000-0000.', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('accounting_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('broker_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('term_pay', models.CharField(choices=[('Quickpay', 'Quickpay'), ('Net 5', 'Net 5'), ('Net 6', 'Net 6'), ('Net 7', 'Net 7'), ('Net 8', 'Net 8'), ('Net 9', 'Net 9'), ('Net 10', 'Net 10'), ('Net 11', 'Net 11'), ('Net 12', 'Net 12'), ('Net 13', 'Net 13'), ('Net 14', 'Net 14'), ('Net 15', 'Net 15'), ('Net 16', 'Net 16'), ('Net 17', 'Net 17'), ('Net 18', 'Net 18'), ('Net 19', 'Net 19'), ('Net 20', 'Net 20'), ('Net 21', 'Net 21'), ('Net 22', 'Net 22'), ('Net 23', 'Net 23'), ('Net 24', 'Net 24'), ('Net 25', 'Net 25'), ('Net 26', 'Net 26'), ('Net 27', 'Net 27'), ('Net 28', 'Net 28'), ('Net 29', 'Net 29'), ('Net 30', 'Net 30')], default='Net 30', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('factoring', models.BooleanField(default=False)),
                ('do_not_use', models.BooleanField(default=False)),
                ('whitelist', models.BooleanField(default=False)),
                ('priority', models.BooleanField(default=False)),
                ('accounts_payable_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_payable_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('accounts_payable_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('accounts_payable_address', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_payable_city', models.CharField(blank=True, max_length=100, null=True)),
                ('accounts_payable_state', models.CharField(blank=True, max_length=100, null=True)),
                ('accounts_payable_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name', 'id'],
            },
        ),
    ]
