# Generated by Django 5.1.1 on 2024-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='term_pay',
            field=models.CharField(choices=[('Quickpay', 'Quickpay'), ('Net 5', 'Net 5'), ('Net 6', 'Net 6'), ('Net 7', 'Net 7'), ('Net 8', 'Net 8'), ('Net 9', 'Net 9'), ('Net 10', 'Net 10'), ('Net 11', 'Net 11'), ('Net 12', 'Net 12'), ('Net 13', 'Net 13'), ('Net 14', 'Net 14'), ('Net 15', 'Net 15'), ('Net 16', 'Net 16'), ('Net 17', 'Net 17'), ('Net 18', 'Net 18'), ('Net 19', 'Net 19'), ('Net 20', 'Net 20'), ('Net 21', 'Net 21'), ('Net 22', 'Net 22'), ('Net 23', 'Net 23'), ('Net 24', 'Net 24'), ('Net 25', 'Net 25'), ('Net 26', 'Net 26'), ('Net 27', 'Net 27'), ('Net 28', 'Net 28'), ('Net 29', 'Net 29'), ('Net 30', 'Net 30')], default='Net 30', max_length=20),
        ),
    ]
