# Generated by Django 5.1.1 on 2024-11-25 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_customer_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cell_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cell_number', message='Cell number must be in the format (000)000-0000.', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mc_number',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_mc_number', message='MC Number must be up to 7 digits long.', regex='^\\d{1,7}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be in the format (000)000-0000.', regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message="ZIP Code must be in the format '12345' or '12345-6789'.", regex='^\\d{5}(-\\d{4})?$')]),
        ),
    ]
