# Generated by Django 5.1.1 on 2025-01-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the vendor.', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Address of the vendor.')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address of the vendor.', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vendor.')),
            ],
        ),
    ]
