# Generated by Django 5.1.4 on 2025-01-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('fax_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('email_password', models.CharField(max_length=50, verbose_name='Email Password')),
                ('client_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Number')),
                ('federal_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Federal Tax ID')),
                ('mc_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor Carrier Number')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Address')),
                ('bank_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank City')),
                ('bank_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Bank Phone')),
                ('bank_fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Bank Fax')),
                ('bank_fraction_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Fraction Number')),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Account Number')),
                ('bank_routing_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Routing Number')),
                ('driver_instructions', models.TextField(blank=True, null=True, verbose_name='Driver Instructions')),
                ('brokerage_notes', models.TextField(blank=True, null=True, verbose_name='Brokerage Notes')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company_favicons/', verbose_name='Company Favicon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Operational Company',
                'verbose_name_plural': 'Operational Companies',
                'ordering': ['name'],
            },
        ),
    ]
