# Generated by Django 5.1.1 on 2024-09-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalcompany',
            name='associated_company',
        ),
    ]
