# Generated by Django 5.1.2 on 2024-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_operationalcompany_associated_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalcompany',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company_favicons/', verbose_name='Company Favicon'),
        ),
    ]
