# Generated by Django 5.1.1 on 2024-09-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipperReceiverCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('shipping_hours', models.CharField(help_text='Example: 9 AM - 6 PM', max_length=100)),
                ('shipping_manager_name', models.CharField(max_length=100)),
                ('shipping_manager_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Rating from 1 to 5')),
                ('load_time', models.DurationField(help_text='Time taken to load a truck (e.g., 2 hours)')),
                ('comments', models.TextField(blank=True, null=True)),
                ('directions', models.TextField(blank=True, help_text='Directions to the shipping/receiving location', null=True)),
                ('do_not_load', models.BooleanField(default=False, help_text="Mark this company as 'Do Not Load'")),
                ('is_shipper', models.BooleanField(default=False)),
                ('is_receiver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('associated_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippers', to='shippers_receivers.shipperreceivercompany')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('associated_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='shippers_receivers.shipperreceivercompany')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_receiver_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippers_receivers.shipperreceivercompany')),
            ],
        ),
    ]
