# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (e.g., Electronics, Furniture).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the category.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a photo of the location.', upload_to='location_photos/')),
                ('description', models.TextField(blank=True, help_text='Description or notes about the photo.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='Day of the week.', max_length=3)),
                ('open_time', models.TimeField(blank=True, help_text='Opening time for the location on the selected day.', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Closing time for the location on the selected day.', null=True)),
            ],
            options={
                'verbose_name': 'Operating Hour',
                'verbose_name_plural': 'Operating Hours',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company or location.', max_length=255)),
                ('address_line1', models.CharField(help_text='Primary address line.', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Secondary address line (optional).', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City where the company is located.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State where the company is located.', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='ZIP/Postal code of the location.', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the company.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address for the company (optional).', max_length=254, null=True)),
                ('load_time', models.DurationField(blank=True, help_text='Time taken to load/unload shipments.', null=True)),
                ('do_not_load', models.BooleanField(default=False, help_text="Mark this location as 'Do Not Load'.")),
                ('no_reefers', models.BooleanField(default=False, help_text='Check if this location does NOT load reefers.')),
                ('plus_code', models.CharField(blank=True, help_text='Google Plus Code for the location.', max_length=50, null=True)),
                ('website', models.URLField(blank=True, help_text='Website URL of the location, if available.', max_length=255, null=True)),
                ('charges_lumper', models.BooleanField(default=False, help_text='Does this location charge for unloading?')),
                ('lumper_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee charged for unloading, if applicable.', max_digits=10, null=True)),
                ('directions', models.TextField(blank=True, help_text='Specific directions to find or navigate to the location.', null=True)),
                ('lat', models.FloatField(blank=True, help_text='Latitude of the location.', null=True)),
                ('lng', models.FloatField(blank=True, help_text='Longitude of the location.', null=True)),
                ('appointment_required', models.BooleanField(default=False, help_text='Indicates if an appointment is required for pickups/deliveries.')),
                ('fcfs', models.BooleanField(default=False, help_text="Indicates if the location operates on a 'First Come, First Served' basis.")),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories for products or location types.', related_name='locations', to='shippers_receivers.category')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('location', models.ForeignKey(help_text='Location associated with this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='location_comments', to='shippers_receivers.location')),
            ],
        ),
    ]
