# Generated by Django 5.1.1 on 2025-01-12 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shippers_receivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcomment',
            name='user',
            field=models.ForeignKey(help_text='User who added the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='user_location_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationphoto',
            name='location',
            field=models.ForeignKey(help_text='Location associated with this photo.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shippers_receivers.location'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='location',
            field=models.ForeignKey(help_text='Location to which these operating hours belong.', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='shippers_receivers.location'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address_line1', 'city', 'state', 'zip_code')},
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together={('location', 'day')},
        ),
    ]
