# Generated by Django 5.1.1 on 2024-10-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='associated_company',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='associated_company',
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
    ]
