# Generated by Django 5.1.1 on 2024-11-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0002_remove_receiver_associated_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipperreceivercompany',
            name='is_receiver',
        ),
        migrations.RemoveField(
            model_name='shipperreceivercompany',
            name='is_shipper',
        ),
    ]
