# Generated by Django 5.1.1 on 2024-12-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment_remove_invoice_associated_company'),
        ('loads', '0005_alter_delivery_delivery_location_and_more'),
        ('shippers_receivers', '0004_category_contact_customer_location_locationphoto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipperReceiverCompany',
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Associated customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='shippers_receivers.customer'),
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories for products or location types', related_name='locations', to='shippers_receivers.category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Associated location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_contacts', to='shippers_receivers.location'),
        ),
        migrations.AddField(
            model_name='locationphoto',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shippers_receivers.location'),
        ),
    ]
