# Generated by Django 5.1.1 on 2024-12-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0005_delete_shipperreceivercompany_contact_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='shipping_hours',
        ),
        migrations.AddField(
            model_name='location',
            name='shipping_hours_from',
            field=models.TimeField(blank=True, help_text='Start of shipping hours', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='shipping_hours_to',
            field=models.TimeField(blank=True, help_text='End of shipping hours', null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
