# Generated by Django 5.1.1 on 2024-12-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_invoice_associated_customer'),
        ('shippers_receivers', '0006_remove_location_shipping_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
