# Generated by Django 5.1.1 on 2024-12-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0007_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude of the location', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude of the location', null=True),
        ),
    ]
