# Generated by Django 5.1.1 on 2024-12-29 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0008_location_lat_location_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address_line1', 'city', 'state', 'zip_code')},
        ),
        migrations.AddField(
            model_name='location',
            name='plus_code',
            field=models.CharField(blank=True, help_text='Google Plus Code for the location.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL of the location, if available.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the category.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the category (e.g., Electronics, Furniture).', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line1',
            field=models.CharField(help_text='Primary address line.', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Secondary address line (optional).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories for products or location types.', related_name='locations', to='shippers_receivers.category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, help_text='City where the company is located.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='directions',
            field=models.TextField(blank=True, help_text='Specific directions to find or navigate to the location.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='do_not_load',
            field=models.BooleanField(default=False, help_text="Mark this location as 'Do Not Load'."),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for the company (optional).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude of the location.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude of the location.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='load_time',
            field=models.DurationField(blank=True, help_text='Time taken to load/unload shipments.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lumper_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee charged for unloading, if applicable.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of the company or location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='no_reefers',
            field=models.BooleanField(default=False, help_text='Check if this location does NOT load reefers.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the company.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, help_text='State where the company is located.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code of the location.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='description',
            field=models.TextField(blank=True, help_text='Description or notes about the photo.', null=True),
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='image',
            field=models.ImageField(help_text='Upload a photo of the location.', upload_to='location_photos/'),
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='location',
            field=models.ForeignKey(help_text='Location associated with this photo.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shippers_receivers.location'),
        ),
        migrations.CreateModel(
            name='LocationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('location', models.ForeignKey(help_text='Location associated with this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='location_comments', to='shippers_receivers.location')),
                ('user', models.ForeignKey(help_text='User who added the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='user_location_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='location',
            name='shipping_hours_from',
        ),
        migrations.RemoveField(
            model_name='location',
            name='shipping_hours_to',
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='Day of the week.', max_length=3)),
                ('open_time', models.TimeField(blank=True, help_text='Opening time for the location on the selected day.', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Closing time for the location on the selected day.', null=True)),
                ('location', models.ForeignKey(help_text='Location to which these operating hours belong.', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='shippers_receivers.location')),
            ],
            options={
                'verbose_name': 'Operating Hour',
                'verbose_name_plural': 'Operating Hours',
                'unique_together': {('location', 'day')},
            },
        ),
    ]
