# Generated by Django 5.1.1 on 2024-12-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0009_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='plus_code',
            field=models.CharField(blank=True, help_text='Google Plus Code for the location.', max_length=50, null=True),
        ),
    ]
