# Generated by Django 5.1.1 on 2024-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers_receivers', '0010_alter_location_plus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='appointment_required',
            field=models.BooleanField(default=False, help_text='Indicates if an appointment is required for pickups/deliveries.'),
        ),
        migrations.AddField(
            model_name='location',
            name='fcfs',
            field=models.BooleanField(default=False, help_text="Indicates if the location operates on a 'First Come, First Served' basis."),
        ),
    ]
