# Generated by Django 5.1.1 on 2024-12-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('superadmin', 'Superadmin'), ('dispatcher', 'Dispatcher'), ('agent', 'Agent'), ('accountant', 'Accountant'), ('safety', 'Safety'), ('recruiter', 'Recruiter')], max_length=50),
        ),
    ]
