# Generated by Django 5.1.1 on 2025-01-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0001_initial'),
        ('companies', '0003_operationalcompany_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name or identifier for the truck (e.g., 'Truck #1').", max_length=100)),
                ('license_plate', models.CharField(help_text='The license plate of the truck.', max_length=20, unique=True)),
                ('manufacturer', models.CharField(help_text="The manufacturer of the truck (e.g., 'Volvo', 'Freightliner').", max_length=100)),
                ('year', models.PositiveIntegerField(help_text='The year the truck was manufactured.')),
                ('vin', models.CharField(help_text='The Vehicle Identification Number (VIN) of the truck.', max_length=17, unique=True)),
                ('truck_number', models.CharField(blank=True, help_text='Internal truck number or Samsara vehicle ID (if integrated).', max_length=20, null=True)),
                ('samsara_device_id', models.CharField(blank=True, help_text='Unique Samsara device ID for GPS tracking.', max_length=50, null=True, unique=True)),
                ('inspection_due', models.DateField(help_text='The date when the next inspection is due.')),
                ('registration_exp', models.DateField(help_text="The expiration date of the truck's registration.")),
                ('insurance_exp', models.DateField(help_text="The expiration date of the truck's insurance policy.")),
                ('fuel_type', models.CharField(blank=True, help_text="The type of fuel used by the truck (e.g., 'Diesel', 'Gasoline').", max_length=50)),
                ('tire_size', models.CharField(blank=True, help_text="The size of the truck's tires.", max_length=50)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, help_text='The length of the truck in feet.', max_digits=5, null=True)),
                ('axles', models.PositiveIntegerField(blank=True, help_text='The number of axles the truck has.', null=True)),
                ('color', models.CharField(blank=True, help_text='The color of the truck.', max_length=30)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, help_text="The truck's gross weight in pounds.", max_digits=10, null=True)),
                ('unladen_weight', models.DecimalField(blank=True, decimal_places=2, help_text="The truck's unladen (empty) weight in pounds.", max_digits=10, null=True)),
                ('acquired_date', models.DateField(blank=True, help_text='The date the truck was acquired.', null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='The monetary value of the truck.', max_digits=15, null=True)),
                ('downpayment', models.DecimalField(blank=True, decimal_places=2, help_text='The down payment made on the truck.', max_digits=15, null=True)),
                ('sold_date', models.DateField(blank=True, help_text='The date the truck was sold, if applicable.', null=True)),
                ('sold_value', models.DecimalField(blank=True, decimal_places=2, help_text='The sale value of the truck, if applicable.', max_digits=15, null=True)),
                ('carrier', models.ForeignKey(blank=True, help_text='The carrier associated with the truck (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='carriers.carrier')),
                ('owner', models.ForeignKey(help_text='The operational company that owns the truck.', on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='companies.operationalcompany')),
            ],
        ),
    ]
