# Generated by Django 5.1.1 on 2025-01-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type of inspection.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details about the inspection type.')),
            ],
        ),
        migrations.RemoveField(
            model_name='truck',
            name='acquired_date',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='axles',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='downpayment',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='inspection_due',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='insurance_exp',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='length_ft',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='registration_exp',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='samsara_device_id',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='sold_value',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='tire_size',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='truck_number',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='unladen_weight',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='value',
        ),
        migrations.AddField(
            model_name='truck',
            name='annual_insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual insurance cost.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='annual_plate_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual plate cost.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='apu_installed',
            field=models.BooleanField(default=False, help_text='Indicates if an APU is installed.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='dashcam_installed',
            field=models.BooleanField(default=False, help_text='Indicates if a dashcam is installed.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_card',
            field=models.CharField(blank=True, help_text='Assigned fuel card.', max_length=50),
        ),
        migrations.AddField(
            model_name='truck',
            name='insurance_renewal_date',
            field=models.DateField(blank=True, help_text='Insurance renewal date.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='integration_id',
            field=models.CharField(blank=True, help_text='Unique integration ID to link the truck to Samsara or other telematics systems.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='is_leased',
            field=models.BooleanField(default=False, help_text='Indicates if the truck is leased.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='is_out_of_service',
            field=models.BooleanField(default=False, help_text='Indicates if the truck is out of service.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='leased_to',
            field=models.CharField(blank=True, help_text='Name of the company the truck is leased to.', max_length=255),
        ),
        migrations.AddField(
            model_name='truck',
            name='out_of_service_reason',
            field=models.TextField(blank=True, help_text='Reason for being out of service.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='owner_operated',
            field=models.BooleanField(default=True, help_text='Indicates if the truck is owner-operated.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='starting_mileage',
            field=models.PositiveIntegerField(default=0, help_text='Starting mileage when the truck was purchased.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='sub_leased',
            field=models.BooleanField(default=False, help_text='Indicates if the truck is sub-leased.'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='manufacturer',
            field=models.CharField(help_text='The manufacturer of the truck.', max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='name',
            field=models.CharField(help_text='The name or identifier for the truck.', max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(help_text='The Vehicle Identification Number (VIN).', max_length=17, unique=True),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the expense.')),
                ('date', models.DateField(help_text='Date of the expense.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the expense.', max_digits=10)),
                ('document', models.FileField(blank=True, help_text='Attached receipt or document.', upload_to='truck_expenses/')),
                ('truck', models.ForeignKey(help_text='The truck associated with the expense.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(help_text='Date when the inspection was performed.')),
                ('expiration_date', models.DateField(help_text='Expiration date of the inspection.')),
                ('document', models.FileField(blank=True, help_text='Attached inspection document.', upload_to='truck_inspections/')),
                ('truck', models.ForeignKey(help_text='The truck being inspected.', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='trucks.truck')),
                ('inspection_type', models.ForeignKey(help_text='Type of inspection.', on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='trucks.inspectiontype')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the maintenance activity.')),
                ('date', models.DateField(help_text='Date of maintenance.')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of the maintenance.', max_digits=10)),
                ('document', models.FileField(blank=True, help_text='Attached maintenance receipt or document.', upload_to='truck_maintenance/')),
                ('truck', models.ForeignKey(help_text='The truck being maintained.', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='trucks.truck')),
            ],
        ),
        migrations.CreateModel(
            name='OutOfServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for taking the truck out of service.')),
                ('date_start', models.DateField(help_text='Date when the truck was taken out of service.')),
                ('date_end', models.DateField(blank=True, help_text='Date when the truck was put back in service.', null=True)),
                ('truck', models.ForeignKey(help_text='The truck taken out of service.', on_delete=django.db.models.deletion.CASCADE, related_name='out_of_service_history', to='trucks.truck')),
            ],
        ),
    ]
