# Generated by Django 5.1.1 on 2025-01-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_inspectiontype_remove_truck_acquired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='active_safety_system_note',
            field=models.TextField(blank=True, help_text='Active safety system note from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='adaptive_cruise_control_acc',
            field=models.CharField(blank=True, help_text='Adaptive cruise control (ACC) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='adaptive_driving_beam_adb',
            field=models.CharField(blank=True, help_text='Adaptive driving beam (ADB) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='additional_error_text',
            field=models.TextField(blank=True, help_text='Additional error text from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='anti_lock_braking_system_abs',
            field=models.CharField(blank=True, help_text='Anti-lock braking system (ABS) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='auto_reverse_system_for_windows_and_sunroofs',
            field=models.CharField(blank=True, help_text='Auto-reverse system for windows/sunroofs from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='automatic_crash_notification_acn_advanced_automatic_crash_notification_aacn',
            field=models.CharField(blank=True, help_text='ACN/AACN from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='automatic_pedestrian_alerting_sound_for_hybrid_and_ev_only',
            field=models.CharField(blank=True, help_text='Pedestrian alerting sound (Hybrid/EV) from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='axle_configuration',
            field=models.CharField(blank=True, help_text='Axle configuration from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='axles',
            field=models.CharField(blank=True, help_text='Axles from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='backup_camera_decoded',
            field=models.CharField(blank=True, help_text='Backup camera from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='base_price',
            field=models.CharField(blank=True, help_text='Base price from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_current_amps_from',
            field=models.CharField(blank=True, help_text='Battery current (amps) (from) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_current_amps_to',
            field=models.CharField(blank=True, help_text='Battery current (amps) (to) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_energy_kwh_from',
            field=models.CharField(blank=True, help_text='Battery energy (kWh) (from) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_energy_kwh_to',
            field=models.CharField(blank=True, help_text='Battery energy (kWh) (to) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_type',
            field=models.CharField(blank=True, help_text='Battery type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_voltage_volts_from',
            field=models.CharField(blank=True, help_text='Battery voltage (volts) (from) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='battery_voltage_volts_to',
            field=models.CharField(blank=True, help_text='Battery voltage (volts) (to) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='bed_length_inches',
            field=models.CharField(blank=True, help_text='Bed length (inches) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='bed_type',
            field=models.CharField(blank=True, help_text='Bed type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='blind_spot_intervention_bsi',
            field=models.CharField(blank=True, help_text='Blind spot intervention (BSI) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='blind_spot_warning_bsw',
            field=models.CharField(blank=True, help_text='Blind spot warning (BSW) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='body_class',
            field=models.CharField(blank=True, help_text='Body class from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='brake_system_description',
            field=models.TextField(blank=True, help_text='Brake system description from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='brake_system_type',
            field=models.CharField(blank=True, help_text='Brake system type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='bus_floor_configuration_type',
            field=models.CharField(blank=True, help_text='Bus floor configuration from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='bus_length_feet',
            field=models.CharField(blank=True, help_text='Bus length (feet) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='bus_type',
            field=models.CharField(blank=True, help_text='Bus type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='cab_type_decoded',
            field=models.CharField(blank=True, help_text='Cab type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='charger_level',
            field=models.CharField(blank=True, help_text='Charger level from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='charger_power_kw',
            field=models.CharField(blank=True, help_text='Charger power (kW) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='cooling_type',
            field=models.CharField(blank=True, help_text='Cooling type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='crash_imminent_braking_cib',
            field=models.CharField(blank=True, help_text='Crash imminent braking (CIB) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='curb_weight_pounds',
            field=models.CharField(blank=True, help_text='Curb weight (pounds) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='curtain_air_bag_locations',
            field=models.CharField(blank=True, help_text='Curtain air bag locations from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='custom_motorcycle_type',
            field=models.CharField(blank=True, help_text='Custom motorcycle type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='daytime_running_light_drl',
            field=models.CharField(blank=True, help_text='Daytime running light (DRL) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='decoded_make',
            field=models.CharField(blank=True, help_text='Make from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='decoded_model',
            field=models.CharField(blank=True, help_text='Model from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='decoded_model_year',
            field=models.CharField(blank=True, help_text='Model year from decoding.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='destination_market',
            field=models.CharField(blank=True, help_text='Destination market from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='displacement_cc',
            field=models.CharField(blank=True, help_text='Displacement (cc) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='displacement_ci',
            field=models.CharField(blank=True, help_text='Displacement (ci) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='displacement_l',
            field=models.CharField(blank=True, help_text='Displacement (l) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='doors',
            field=models.CharField(blank=True, help_text='Doors info from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='drive_type_decoded',
            field=models.CharField(blank=True, help_text='Drive type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='dynamic_brake_support_dbs',
            field=models.CharField(blank=True, help_text='Dynamic brake support (DBS) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='electrification_level',
            field=models.CharField(blank=True, help_text='Electrification level from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='electronic_stability_control_esc',
            field=models.CharField(blank=True, help_text='Electronic stability control (ESC) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_brake_hp_from',
            field=models.CharField(blank=True, help_text='Engine brake (hp) from (decoding).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_brake_hp_to',
            field=models.CharField(blank=True, help_text='Engine brake (hp) to (decoding).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_configuration_decoded',
            field=models.CharField(blank=True, help_text='Engine configuration from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_manufacturer_decoded',
            field=models.CharField(blank=True, help_text='Engine manufacturer from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_model_decoded',
            field=models.CharField(blank=True, help_text='Engine model from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_number_of_cylinders_decoded',
            field=models.CharField(blank=True, help_text='Engine number of cylinders from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_power_kw',
            field=models.CharField(blank=True, help_text='Engine power (kW) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_stroke_cycles',
            field=models.CharField(blank=True, help_text='Engine stroke cycles from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='entertainment_system',
            field=models.CharField(blank=True, help_text='Entertainment system info from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code from decoding.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='error_text',
            field=models.TextField(blank=True, help_text='Error text from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='ev_drive_unit',
            field=models.CharField(blank=True, help_text='EV drive unit from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='event_data_recorder_edr',
            field=models.CharField(blank=True, help_text='Event data recorder (EDR) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='forward_collision_warning_fcw',
            field=models.CharField(blank=True, help_text='Forward collision warning (FCW) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='front_air_bag_locations',
            field=models.CharField(blank=True, help_text='Front air bag locations from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_delivery_fuel_injection_type',
            field=models.CharField(blank=True, help_text='Fuel delivery / Fuel injection type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_type_primary_decoded',
            field=models.CharField(blank=True, help_text='Fuel type (primary) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_type_secondary',
            field=models.CharField(blank=True, help_text='Fuel type (secondary) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='gross_combination_weight_rating_from',
            field=models.CharField(blank=True, help_text='Gross combination weight rating (from) from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='gross_combination_weight_rating_to',
            field=models.CharField(blank=True, help_text='Gross combination weight rating (to) from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='gross_vehicle_weight_rating_from',
            field=models.CharField(blank=True, help_text='Gross vehicle weight rating (from) from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='gross_vehicle_weight_rating_to',
            field=models.CharField(blank=True, help_text='Gross vehicle weight rating (to) from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='headlamp_light_source',
            field=models.CharField(blank=True, help_text='Headlamp light source from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='keyless_ignition',
            field=models.CharField(blank=True, help_text='Keyless ignition from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='knee_air_bag_locations',
            field=models.CharField(blank=True, help_text='Knee air bag locations from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='lane_centering_assistance',
            field=models.CharField(blank=True, help_text='Lane centering assistance from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='lane_departure_warning_ldw',
            field=models.CharField(blank=True, help_text='Lane departure warning (LDW) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='lane_keeping_assistance_lka',
            field=models.CharField(blank=True, help_text='Lane keeping assistance (LKA) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='manufacturer_name',
            field=models.CharField(blank=True, help_text='Manufacturer name from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='motorcycle_chassis_type',
            field=models.CharField(blank=True, help_text='Motorcycle chassis type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='motorcycle_suspension_type',
            field=models.CharField(blank=True, help_text='Motorcycle suspension type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='non_land_use',
            field=models.CharField(blank=True, help_text='Non-land use info from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='note',
            field=models.TextField(blank=True, help_text='Note from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_battery_cells_per_module',
            field=models.CharField(blank=True, help_text='Number of battery cells per module from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_battery_modules_per_pack',
            field=models.CharField(blank=True, help_text='Number of battery modules per pack from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_battery_packs_per_vehicle',
            field=models.CharField(blank=True, help_text='Number of battery packs per vehicle from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_seat_rows',
            field=models.CharField(blank=True, help_text='Number of seat rows from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_seats',
            field=models.CharField(blank=True, help_text='Number of seats from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_wheels',
            field=models.CharField(blank=True, help_text='Number of wheels from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='other_battery_info',
            field=models.TextField(blank=True, help_text='Other battery info from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='other_bus_info',
            field=models.TextField(blank=True, help_text='Other bus info from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='other_engine_info',
            field=models.TextField(blank=True, help_text='Other engine info from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='other_motorcycle_info',
            field=models.TextField(blank=True, help_text='Other motorcycle info from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='other_restraint_system_info',
            field=models.TextField(blank=True, help_text='Other restraint system info from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='other_trailer_info',
            field=models.TextField(blank=True, help_text='Other trailer info from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='parking_assist_decoded',
            field=models.CharField(blank=True, help_text='Parking assist from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='pedestrian_automatic_emergency_braking_paeb',
            field=models.CharField(blank=True, help_text='Pedestrian automatic emergency braking (PAEB) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='plant_city',
            field=models.CharField(blank=True, help_text='Plant city from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='plant_company_name',
            field=models.CharField(blank=True, help_text='Plant company name from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='plant_country',
            field=models.CharField(blank=True, help_text='Plant country from decoding.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='plant_state',
            field=models.CharField(blank=True, help_text='Plant state from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='possible_values',
            field=models.TextField(blank=True, help_text='Possible values from decoding.', null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='pretensioner',
            field=models.CharField(blank=True, help_text='Pretensioner from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='rear_automatic_emergency_braking',
            field=models.CharField(blank=True, help_text='Rear automatic emergency braking from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='rear_cross_traffic_alert',
            field=models.CharField(blank=True, help_text='Rear cross traffic alert from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='sae_automation_level_from',
            field=models.CharField(blank=True, help_text='SAE automation level (from) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='sae_automation_level_to',
            field=models.CharField(blank=True, help_text='SAE automation level (to) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='seat_belt_type',
            field=models.CharField(blank=True, help_text='Seat belt type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='seat_cushion_air_bag_locations',
            field=models.CharField(blank=True, help_text='Seat cushion air bag locations from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='semiautomatic_headlamp_beam_switching',
            field=models.CharField(blank=True, help_text='Semiautomatic headlamp beam switching from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='series',
            field=models.CharField(blank=True, help_text='Series from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='series2',
            field=models.CharField(blank=True, help_text='Second series from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='side_air_bag_locations',
            field=models.CharField(blank=True, help_text='Side air bag locations from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='steering_location',
            field=models.CharField(blank=True, help_text='Steering location from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='suggested_vin',
            field=models.CharField(blank=True, help_text='Suggested VIN from decode.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='tire_pressure_monitoring_system_tpms_type',
            field=models.CharField(blank=True, help_text='Tire pressure monitoring system (TPMS) type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='top_speed_mph',
            field=models.CharField(blank=True, help_text='Top speed (mph) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='track_width_inches',
            field=models.CharField(blank=True, help_text='Track width (inches) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='traction_control_decoded',
            field=models.CharField(blank=True, help_text='Traction control from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='trailer_body_type',
            field=models.CharField(blank=True, help_text='Trailer body type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='trailer_length_feet',
            field=models.CharField(blank=True, help_text='Trailer length (feet) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='trailer_type_connection',
            field=models.CharField(blank=True, help_text='Trailer type connection from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='transmission_speeds',
            field=models.CharField(blank=True, help_text='Transmission speeds from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='transmission_style',
            field=models.CharField(blank=True, help_text='Transmission style from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='trim',
            field=models.CharField(blank=True, help_text='Trim from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='trim2',
            field=models.CharField(blank=True, help_text='Second trim from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='turbo',
            field=models.CharField(blank=True, help_text='Turbo info from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='valve_train_design',
            field=models.CharField(blank=True, help_text='Valve train design from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='vehicle_descriptor',
            field=models.CharField(blank=True, help_text='Vehicle descriptor from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Vehicle type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='wheel_base_inches_from',
            field=models.CharField(blank=True, help_text='Wheel base (inches) (from) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='wheel_base_inches_to',
            field=models.CharField(blank=True, help_text='Wheel base (inches) (to) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='wheel_base_type',
            field=models.CharField(blank=True, help_text='Wheel base type from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='wheel_size_front_inches',
            field=models.CharField(blank=True, help_text='Wheel size front (inches) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='wheel_size_rear_inches',
            field=models.CharField(blank=True, help_text='Wheel size rear (inches) from decoding.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='windows',
            field=models.CharField(blank=True, help_text='Windows info from decoding.', max_length=50, null=True),
        ),
    ]
