# Generated by Django 5.1.1 on 2025-01-03 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_operationalcompany_favicon'),
        ('trucks', '0003_truck_active_safety_system_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The operational company that owns the truck.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='companies.operationalcompany'),
        ),
    ]
